In [1]:
import boto3
import os
from io import StringIO, BytesIO
import pandas as pd
from library import InsertDataToDataLake

In [2]:
df = pd.read_csv('enhanced_anxiety_dataset.csv')
df

,Age,Gender,Occupation,SleepHours,PhysicalActivity,CaffeineIntake,AlcoholConsumption,Smoking,FamilyHistory,StressLevel,HeartRate,BreathingRate,SweatingLevel,Dizziness,Medication,TherapySessions,DietQuality,AnxietyLevel
0,29,Female,Artist,6.0,2.7,181,10,Yes,No,10,114,14,4,No,Yes,3,7,5
1,46,Other,Nurse,6.2,5.7,200,8,Yes,Yes,1,62,23,2,Yes,No,2,8,3
2,64,Male,Other,5.0,3.7,117,4,No,Yes,1,91,28,3,No,No,1,1,1
3,20,Female,Scientist,5.8,2.8,360,6,Yes,No,4,86,17,3,No,No,0,1,2
4,49,Female,Other,8.2,2.3,247,4,Yes,No,1,98,19,4,Yes,Yes,1,3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10995,23,Female,Engineer,6.1,3.1,566,9,Yes,No,8,91,28,1,Yes,Yes,1,3,6
10996,50,Other,Teacher,6.6,3.6,64,17,Yes,No,7,95,17,3,No,No,2,7,3
10997,29,Male,Nurse,6.7,6.9,159,14,No,No,8,72,16,1,Yes,Yes,2,7,4
10998,53,Other,Artist,5.7,2.7,248,8,No,No,4,112,28,3,Yes,Yes,1,2,4
10999,56,Other,Teacher,6.1,1.1,205,11,No,No,1,66,13,3,No,No,2,8,2

In [3]:
chunk_1 = df.iloc[0:100]
chunk_2 = df.iloc[100:200]

In [4]:
buffer_1 = StringIO()
buffer_2 = StringIO()

In [5]:
chunk_1.to_csv(buffer_1, index=False)
chunk_2.to_csv(buffer_2, index=False)

In [6]:
writer_1 = InsertDataToDataLake(
    module = 'anxietyapp',
    file_buffer=buffer_1.getvalue(),
    folder_name='anxiety',
    file_name='anxiety',
    file_type='csv'
)
writer_2 = InsertDataToDataLake(
    module = 'anxietyapp',
    file_buffer=buffer_1.getvalue(),
    folder_name='anxiety',
    file_name='anxiety2',
    file_type='csv'
)
writer_1.push_data(), writer_2.push_data()

(None, None)